# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cda381262bcb519e8b514eda442336468c98d212d9670c89ac36d18c8665cca4ee10e71d725fa8d0c4c23e38eb39bf45adba24714037d83dc8d837a19df1dcc

test:
  secret_key_base: 80cd70c215e94a04d4026d080b64a4ace10413e158d89cbf0a56263ba7ff9142e01118bff54eaebaa24ad24d6be5d7c7dbc8c2e3c46174cfa6e97e39bd7cce63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
